### PR TITLE
✨ v2.7.3

### PR DESCRIPTION
**Pull request by Ludy87**
- add Emoji for Message Markdown
- update user-agents
- add mapbox with API_KEY
- clean up and more

### CODE REVIEW

**Comment by bluenazgul** [comment]
I dont know what iam doing wrong, even with the Automation and Markdown Sample (changed to the correct Sensor for my watch) the Markdown Card stays empty, the Message Sensor counter changed to 0 but the Sensor Attributes Shows the Last Receiver and send Messages

**Comment by Ludy87** [comment]
is nothing displayed in the browser or in the app?

**Comment by bluenazgul** [comment]
> is nothing displayed in the browser or in the app?

both, inside the app and and chrome browser

**Comment by Ludy87** [comment]
if you go to the message sensor, and then to attributes, is there a list?

**Comment by bluenazgul** [comment]
> if you go to the message sensor, and then to attributes, is there a list?

yes, a list is shown there - strange is that after todays update the message sensor changed from "12" Yesterday to "0" today, even that i send 3 new messages to the watch using the app today, this three messages are shown inside the list

**Comment by Ludy87** [comment]
if a list is shown there, then something is wrong in the markdown layout. The counter is not reset by the integration!

**Comment by bluenazgul** [comment]
I used your Markdown File from Yesterday and changed the
sensor.xxx_xplora....... on top to the Message Sensor of my watch.

Ludy ***@***.***> schrieb am Do., 23. Feb. 2023, 09:22:

**Comment by Ludy87** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
